# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [0]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到 1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])          
y = np.array([[0,0,1,1]]).T

In [0]:
np.random.seed(1)
#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣）
w0 = 2*np.random.random((3,3)) - 1
w1 = 2*np.random.random((3,3)) - 1

w0_history = [w0]
w1_history = [w1]

神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [6]:
for _ in range(10000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,w0))
    l2 = nonlin(np.dot(l1,w1))
    '''
    新增
    l2_error 該值說明了神經網路預測時“丟失”的數目。
    l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。
    '''
 
    # how much did we miss?
    l1_error = y - l1
    l2_error = y - l2
 
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    l2_delta = l2_error * nonlin(l2,True)
    
    # update weights
    w0 += np.dot(l0.T,l1_delta)
    w1 += np.dot(l1.T,l2_delta)
    
print("Output After Training:")
print('L1:', l1)
print()
print('L2:', l2)

Output After Training:
L1: [[0.00966835 0.00966881 0.00967224]
 [0.00786365 0.0078617  0.00786433]
 [0.99359085 0.99359281 0.99359069]
 [0.9921173  0.99211737 0.99211461]]
L2: [[0.50813907 0.50813856 0.50813891]
 [0.5066189  0.50661825 0.506619  ]
 [0.96596356 0.96596359 0.96596355]
 [0.96579992 0.96579993 0.96579993]]



In [10]:
syn0_history

[array([[ 9.67288347,  9.67314247,  9.67245244],
        [-0.20842777, -0.2087252 , -0.2087456 ],
        [-4.62923331, -4.62918553, -4.62882797]])]